[project]
name = "openapi-example-python"
version = "0.1.0"
description = "Working with EDA OpenAPI specification"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "httpx==0.28.1",
    "pydantic==2.10.5",
    "rich>=13.9.4",
]
