# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/main/apps/components.eda.nokia.com/v1alpha1/components.json
#   timestamp: 2025-01-22T14:25:48+00:00
