# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/main/apps/topologies.eda.nokia.com/v1alpha1/topologies.json
#   timestamp: 2025-01-22T14:01:37+00:00
