# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/main/apps/interfaces.eda.nokia.com/v1alpha1/interfaces.json
#   timestamp: 2025-01-22T14:01:16+00:00
