# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/eda-labs/openapi/main/apps/routingpolicies.eda.nokia.com/v1alpha1/routingpolicies.json
#   timestamp: 2025-01-22T14:26:11+00:00
